### ISSUE TITLE
in memory panic stackshot. How to deal with this?

### ISSUE THREAD

**Issue by londons123** [Necromancer2Point0/MSI-GS66-OC-New-Dawn#10]
![微信图片_20221009221140](https://user-images.githubusercontent.com/41947407/194762066-8cd34d30-a722-4a1e-aab9-ae8c0bae3ae5.jpg)
How to deal with this?

**Comment by Necromancer2Point0** [comment]
Read up on Dortania's OC guide, double checking everything is in order, paying close attention to areas where our specs differ if applicable. Use the tools I mentioned in another post (OC validate, config compare...) and see if anything comes up. Successful hackintoshing is a real learning experience but rewarding in the long run.
