### ISSUE TITLE
Better Trackpad (Scrolling, Gesture)

### ISSUE THREAD

**Issue by edmondt** [Necromancer2Point0/MSI-GS66-OC-New-Dawn#5]
I disabled the following VoodooInput.kext in the config, downloaded the latest VoodooI2C.kext, VoodooPS2Controller.kext and it made the scrolling, gestures a lot smoother.

			<dict>
				<key>BundlePath</key>
				<string>VoodooInput.kext</string>
				<key>Comment</key>
				<string></string>
				<key>Disabled</key>
				<true/>
				<key>ExecutablePath</key>
				<string>Contents/MacOS/VoodooInput</string>
				<key>MaxKernel</key>
				<string></string>
				<key>MinKernel</key>
				<string></string>
				<key>PlistPath</key>
				<string>Contents/Info.plist</string>
			</dict>

**Comment by Necromancer2Point0** [comment]
Tried your suggestions in recent testings. Completely broke hotkeys (including basic copy-paste functions) and provided no noticeable improvements with tracking or scrolling. Whilst it might be necessary for your newer MacOS version, it is incompatible with what I'm running.
