### ISSUE TITLE
Failed to upgrade to lastest opencore 0.7.8 Catalina

### ISSUE THREAD

**Issue by Okenshield** [Necromancer2Point0/MSI-GS66-OC-New-Dawn#7]
I have MSI GS66 10SE.
CPU: i7-10750h
GPU: UHD 630
Display: 15.6" 1080p 144hz
I had successfully installed macOS Catalina 10.5.7 using your build. But when I try to upgrade to your latest build, it stuck at this [screen]( https://imgur.com/a/e3ofgG5). 

log:
[opencore-2022-02-27-032127.txt](https://github.com/Necromancer2Point0/MSI-GS66-OC-New-Dawn/files/8148595/opencore-2022-02-27-032127.txt)

**Comment by Necromancer2Point0** [comment]
Hi,

Glad to hear you were able to successfully install with an older build and sorry to hear you're facing issues with the current version! Hackintoshing is a lot of trial and error + tweaking. What works for me may not work for you despite us having extremely similar machines. That said...

This build had some pretty drastic changes, kext updates, and re-workings of some core code. I spent a whole day refining and validating that there were no errors in the plist (eg with tools like OC validate, config compare...) so I'm pretty confident in its stability. You may need to tweak some things specifically for the specs of your machine and / or double check you've updated correctly.

Some questions and suggestions:

1) Did you replace the **entire** EFI folder with the current version and re-enter your serials, ROM etc? The config.plist has significantly changed and older kext versions are incompatible with the current OC version. You need to update / replace the **entire** EFI then re-enter your personal serials.

2) Consult the misc folder and compare my bios settings with yours. Hackintoshing is very finnicky and even a small difference here can make or break a build. Also look at the tweaks folder. Have you made the appropriate adjustments? Did you undervolt your machine? (if not, may need to edit out the undervolting kexts etc)

3) Read up on Dortania's OC guide, double checking everything is in order, paying close attention to areas where our specs differ. Use the same tools I mentioned above (OC validate, config compare...) and see if anything comes up. Successful hackintoshing is a real learning experience lol but rewarding in the long run.

Best of luck!
