### ISSUE TITLE
also i7 10875h？

### ISSUE THREAD

**Issue by xmnily** [Necromancer2Point0/MSI-GS66-OC-New-Dawn#8]
my computer is gs66 10sf. 240hz I wonder the efi can i use. thank you！

**Comment by Necromancer2Point0** [comment]
Hi,

Although this EFI is specifically configured to my own specifications (listed in the table in the README), as we are using very similar machines, it should work for you with a few adjustments.

Please consult Dortania's OC guide if you're unsure and double check the config.plist. Hackintoshing is a lot of trial and error so you may (or may not) need to adjust any part where our specs differ (eg i7-10750H v i7-10875h, 300hz v 240hz...).

Also, remember to generate new serials and enter them into the appropriate fields. All the best!
